services:
  base_server:
    build: Server
    environment:
      - FACE_API=http://face_server:8000/face_api/v1
      - STORE_API=http://nginx/store_api/v1
      - DB_URI=postgresql+asyncpg://postgres:root@base_db:5432/TransportEngineers
      - DB_URI_ALEMBIC=postgresql+psycopg2://postgres:root@base_db:5432/TransportEngineers
      - REDIS_URI=redis://redis:6379
      - KEYCLOAK_INTROSPECTIVE_ENDPOINT=http://nginx:80/keycloak/realms/ai_site/protocol/openid-connect/token/introspect
    depends_on:
      base_db:
        condition: service_started
      redis:
        condition: service_started
      face_server:
        condition: service_started
      store_server:
        condition: service_started
  store_server:
    build: StoresServer
    environment:
      - DB_URI=postgresql+asyncpg://postgres:root@store_db:5432/TransportEngineersStores
      - DB_URI_ALEMBIC=postgresql+psycopg2://postgres:root@store_db:5432/TransportEngineersStores
      - REDIS_URI=redis://redis:6379
    depends_on:
      store_db:
        condition: service_started
  face_server:
    build: FaceServer
    environment:
      - CHROMA_DB_PORT=8000
      - CHROMA_DB_HOST=chromadb
    volumes:
      - face_model:/root/.insightface/models
    depends_on:
      chromadb:
        condition: service_started
  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./DebugData/static:/app/static
    ports:
      - "8080:80"
    depends_on:
      store_server:
        condition: service_started
      base_server:
        condition: service_started
      face_server:
        condition: service_started
  redis:
    image: "redis:alpine"
  chromadb:
    image: chromadb/chroma
    environment:
      - PERSIST_DIRECTORY=/chroma/chroma
    volumes:
      - chroma_data:/chroma/chroma
  base_db:
    image: postgres:14-alpine
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=TransportEngineers
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - base_data:/var/lib/postgresql/data
  store_db:
    image: postgres:14-alpine
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=TransportEngineersStores
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - stores_data:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8090:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: TheRealAdmin
      KC_BOOTSTRAP_ADMIN_PASSWORD: TheR@alAdmin)
      KC_HTTP_RELATIVE_PATH: /keycloak
    volumes:
      - ./keycloak_realm.json:/opt/keycloak/data/import/main_realm.json
    command:
      - start-dev
      - --import-realm
      - --verbose
      - --hostname 
      - http://localhost:8080/keycloak
  frontend:
    build: Frontend
    ports:
      - "8000:8000"
    environment:
      - auth_redirect_uri=http://nginx/keycloak/realms/ai_site/protocol/openid-connect/auth
      - auth_token_uri=http://nginx/keycloak/realms/ai_site/protocol/openid-connect/token
      - user_info_uri=http://nginx/keycloak/realms/ai_site/protocol/openid-connect/userinfo
volumes:
  base_data:
  stores_data:
  chroma_data:
  face_model: