"""Add code to tickets

Revision ID: 2a35c866d40d
Revises: 77dfd111ef8c
Create Date: 2024-12-31 20:47:20.129147

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a35c866d40d"
down_revision: Union[str, None] = "77dfd111ef8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("code", sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickets", "code")
    # ### end Alembic commands ###
