"""Add destination to ticket

Revision ID: 6d5696cd6d86
Revises: c30599f5d501
Create Date: 2024-08-02 13:12:48.557671

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d5696cd6d86"
down_revision: Union[str, None] = "c30599f5d501"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tickets", sa.Column("destination_id", sa.String(length=60), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickets", "destination_id")
    # ### end Alembic commands ###
