"""Add train_date to train_stores table

Revision ID: 77dfd111ef8c
Revises: 69ef8220180a
Create Date: 2024-10-12 19:53:19.151678

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77dfd111ef8c"
down_revision: Union[str, None] = "69ef8220180a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "train_stores",
        sa.Column("train_date", sa.DateTime(timezone=True), nullable=False),
    )
    op.alter_column("train_stores", "store_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "train_stores", "train_number", existing_type=sa.INTEGER(), nullable=False
    )
    # op.drop_constraint('train_stores_store_id_fkey', 'train_stores', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "train_stores_store_id_fkey", "train_stores", "engineers", ["store_id"], ["id"]
    )
    op.alter_column(
        "train_stores", "train_number", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("train_stores", "store_id", existing_type=sa.UUID(), nullable=True)
    op.drop_column("train_stores", "train_date")
    # ### end Alembic commands ###
