"""Add auth cards

Revision ID: 8cb901049479
Revises: bb27688d1da1
Create Date: 2024-07-26 00:12:36.069526

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cb901049479"
down_revision: Union[str, None] = "bb27688d1da1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_cards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("engineer_id", sa.UUID(), nullable=True),
        sa.Column("key", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["engineer_id"],
            ["engineers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auth_cards")
    # ### end Alembic commands ###
