"""Create base model

Revision ID: bb27688d1da1
Revises:
Create Date: 2024-07-23 16:57:47.276227

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb27688d1da1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "active_stores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("public_key", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "engineers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("login", sa.String(length=60), nullable=True),
        sa.Column("password", sa.String(length=60), nullable=True),
        sa.Column("privileges", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
    )
    op.create_table(
        "robots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("robot_model_id", sa.String(length=60), nullable=True),
        sa.Column("robot_model_name", sa.String(length=60), nullable=True),
        sa.Column("public_key", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("robot_model_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("train_number", sa.Integer(), nullable=True),
        sa.Column("wagon_number", sa.Integer(), nullable=True),
        sa.Column("place_number", sa.Integer(), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("station_id", sa.String(length=60), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tickets")
    op.drop_table("users")
    op.drop_table("robots")
    op.drop_table("engineers")
    op.drop_table("active_stores")
    # ### end Alembic commands ###
