"""Add start date for ticket

Revision ID: f6815aa45b7a
Revises: 6d5696cd6d86
Create Date: 2024-08-03 19:43:06.403262

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f6815aa45b7a'
down_revision: Union[str, None] = '6d5696cd6d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'start_date')
    # ### end Alembic commands ###
